### ISSUE TITLE
Build failure - Java heap space - TestProjectEuler

### ISSUE THREAD

**Issue by tamwile** [kspalaiologos/kamilalisp#50]
```
> java --version
openjdk 20.0.2 2023-07-18
OpenJDK Runtime Environment (build 20.0.2+9)
OpenJDK 64-Bit Server VM (build 20.0.2+9, mixed mode, sharing)
```

After running `mvn package` :
```
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< palaiologos:kamilalisp >-----------------------
[INFO] Building kamilalisp 0.3
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.10:prepare-agent (default) @ kamilalisp ---
[INFO] argLine set to -javaagent:$HOME/.m2/repository/org/jacoco/org.jacoco.agent/0.8.10/org.jacoco.agent-0.8.10-runtime.jar=destfile=/path/to/kamilalisp/target/jacoco.exec,excludes=palaiologos/kamilalisp/repl/*.class:palaiologos/kamilalisp/runtime/ide/*.class:palaiologos/kamilalisp/runtime/remote/*.class:palaiologos/kamilalisp/runtime/sh/*.class:palaiologos/kamilalisp/runtime/image/*.class:palaiologos/kamilalisp/runtime/net/*.class:org/**
[INFO] 
[INFO] --- antlr4-maven-plugin:4.13.0:antlr4 (default) @ kamilalisp ---
[INFO] No grammars to process
[INFO] ANTLR 4: Processing source directory /path/to/kamilalisp/src/main/java/palaiologos/kamilalisp/parsers
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ kamilalisp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 10502 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ kamilalisp ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1152 source files to /path/to/kamilalisp/target/classes
[WARNING] /path/to/kamilalisp/src/main/java/org/armedbear/lisp/Lisp.java: Some input files use or override a deprecated API.
[WARNING] /path/to/kamilalisp/src/main/java/org/armedbear/lisp/Lisp.java: Recompile with -Xlint:deprecation for details.
[WARNING] /path/to/kamilalisp/src/main/java/org/armedbear/lisp/Symbol.java: Some input files use or override a deprecated API that is marked for removal.
[WARNING] /path/to/kamilalisp/src/main/java/org/armedbear/lisp/Symbol.java: Recompile with -Xlint:removal for details.
[WARNING] /path/to/kamilalisp/src/main/java/org/armedbear/lisp/Package.java: Some input files use unchecked or unsafe operations.
[WARNING] /path/to/kamilalisp/src/main/java/org/armedbear/lisp/Package.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ kamilalisp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /path/to/kamilalisp/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ kamilalisp ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:3.1.2:test (default-test) @ kamilalisp ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestMath
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.771 s -- in TestMath
[INFO] Running TestRangeFoldScan
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.046 s -- in TestRangeFoldScan
[INFO] Running TestSortDescAsc
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.028 s -- in TestSortDescAsc
[INFO] Running TestTCO
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 s -- in TestTCO
[INFO] Running TestReverseRotate
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s -- in TestReverseRotate
[INFO] Running TestProjectEuler
[ERROR] Java heap space
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 17, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:08 min
[INFO] Finished at: 2023-08-30T09:15:42+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project kamilalisp: 
[ERROR] 
[ERROR] Please refer to /path/to/kamilalisp/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] Java heap space
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Java heap space
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:628)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1203)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1055)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:871)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:298)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
/m/P/p/l/kamilalisp (v0.3) [1]> java --version
openjdk 20.0.2 2023-07-18
OpenJDK Runtime Environment (build 20.0.2+9)
OpenJDK 64-Bit Server VM (build 20.0.2+9, mixed mode, sharing)
```

**Comment by iczelia** [comment]
Hi.
The ProjectEuler implementation is unfortunately very resource demanding, because i have implemented a very naive algorithm. You may want to tell Maven to skip the tests to avoid the error if you are building on a remarkably low power machine.

**Comment by tamwile** [comment]
Hi, thanks.

`mvn package -DskipTests` took around 10 min, i don't know if that's remarkably low power though.
