### ISSUE TITLE
Proguard step fails.

### ISSUE THREAD

**Issue by tamwile** [kspalaiologos/kamilalisp#85]
`java --version`
```sh
openjdk 22 2024-03-19
OpenJDK Runtime Environment (build 22)
OpenJDK 64-Bit Server VM (build 22, mixed mode, sharing)
```

Build fails at the proguard step.

```sh
...
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing /path/to/kamilalisp/target/kamilalisp-0.3.jar with /path/to/kamilalisp/target/kamilalisp-0.3-shaded.jar
[INFO] 
[INFO] --- proguard:2.6.0:proguard (default) @ kamilalisp ---
[INFO] execute ProGuard [-injars, '/path/to/kamilalisp/target/kamilalisp-0.3_proguard_base.jar'(!META-INF/maven/**), -libraryjars, '/home/user/.m2/repository/org/antlr/antlr4-runtime/4.13.1/antlr4-runtime-4.13.1.jar', -libraryjars, '/home/user/.m2/repository/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar', -libraryjars, '/home/user/.m2/repository/ch/obermuhlner/big-math/2.3.2/big-math-2.3.2.jar', -libraryjars, '/home/user/.m2/repository/org/apache/commons/commons-text/1.11.0/commons-text-1.11.0.jar', -libraryjars, '/home/user/.m2/repository/com/google/guava/guava/32.1.3-jre/guava-32.1.3-jre.jar', -libraryjars, '/home/user/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar', -libraryjars, '/home/user/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar', -libraryjars, '/home/user/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar', -libraryjars, '/home/user/.m2/repository/org/checkerframework/checker-qual/3.37.0/checker-qual-3.37.0.jar', -libraryjars, '/home/user/.m2/repository/com/google/errorprone/error_prone_annotations/2.21.1/error_prone_annotations-2.21.1.jar', -libraryjars, '/home/user/.m2/repository/com/google/j2objc/j2objc-annotations/2.8/j2objc-annotations-2.8.jar', -libraryjars, '/home/user/.m2/repository/org/jline/jline-reader/3.26.1/jline-reader-3.26.1.jar', -libraryjars, '/home/user/.m2/repository/org/jline/jline-terminal/3.26.1/jline-terminal-3.26.1.jar', -libraryjars, '/home/user/.m2/repository/org/jline/jline-native/3.26.1/jline-native-3.26.1.jar', -libraryjars, '/home/user/.m2/repository/org/jline/jline-terminal-jni/3.26.1/jline-terminal-jni-3.26.1.jar', -libraryjars, '/home/user/.m2/repository/org/pcollections/pcollections/4.0.1/pcollections-4.0.1.jar', -libraryjars, '/home/user/.m2/repository/org/apache/commons/commons-csv/1.10.0/commons-csv-1.10.0.jar', -libraryjars, '/home/user/.m2/repository/org/apache/commons/commons-compress/1.25.0/commons-compress-1.25.0.jar', -libraryjars, '/home/user/.m2/repository/org/tukaani/xz/1.9/xz-1.9.jar', -libraryjars, '/home/user/.m2/repository/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar', -libraryjars, '/home/user/.m2/repository/org/jgrapht/jgrapht-core/1.5.2/jgrapht-core-1.5.2.jar', -libraryjars, '/home/user/.m2/repository/org/jheaps/jheaps/0.14/jheaps-0.14.jar', -libraryjars, '/home/user/.m2/repository/org/apfloat/apfloat/1.10.1/apfloat-1.10.1.jar', -libraryjars, '/home/user/.m2/repository/rocks/palaiologos/maja/0.2.4/maja-0.2.4.jar', -libraryjars, '/home/user/.m2/repository/com/formdev/flatlaf/3.2.5/flatlaf-3.2.5.jar', -libraryjars, '/home/user/.m2/repository/io/undertow/undertow-core/2.3.10.Final/undertow-core-2.3.10.Final.jar', -libraryjars, '/home/user/.m2/repository/org/jboss/logging/jboss-logging/3.4.3.Final/jboss-logging-3.4.3.Final.jar', -libraryjars, '/home/user/.m2/repository/org/jboss/xnio/xnio-api/3.8.8.Final/xnio-api-3.8.8.Final.jar', -libraryjars, '/home/user/.m2/repository/org/wildfly/common/wildfly-common/1.5.4.Final/wildfly-common-1.5.4.Final.jar', -libraryjars, '/home/user/.m2/repository/org/wildfly/client/wildfly-client-config/1.0.1.Final/wildfly-client-config-1.0.1.Final.jar', -libraryjars, '/home/user/.m2/repository/org/jboss/threads/jboss-threads/3.5.0.Final/jboss-threads-3.5.0.Final.jar', -libraryjars, '/home/user/.m2/repository/io/undertow/undertow-websockets-jsr/2.3.10.Final/undertow-websockets-jsr-2.3.10.Final.jar', -libraryjars, '/home/user/.m2/repository/io/undertow/undertow-servlet/2.3.10.Final/undertow-servlet-2.3.10.Final.jar', -libraryjars, '/home/user/.m2/repository/jakarta/servlet/jakarta.servlet-api/6.0.0/jakarta.servlet-api-6.0.0.jar', -libraryjars, '/home/user/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar', -libraryjars, '/home/user/.m2/repository/jakarta/websocket/jakarta.websocket-api/2.1.0/jakarta.websocket-api-2.1.0.jar', -libraryjars, '/home/user/.m2/repository/jakarta/websocket/jakarta.websocket-client-api/2.1.0/jakarta.websocket-client-api-2.1.0.jar', -outjars, '/path/to/kamilalisp/target/kamilalisp-0.3.jar', -printmapping, '/path/to/kamilalisp/target/proguard_map.txt', -printseeds, '/path/to/kamilalisp/target/proguard_seed.txt', -libraryjars <java.home>/jmods, -keep class org.jline.terminal.** { *; }, -keep class org.jline.utils.** { *; }, -keep class org.tukaani.xz.MemoryLimitException { *; }, -keep class org.tukaani.xz.SingleXZInputStream { *; }, -keep class org.tukaani.xz.XZ { *; }, -keep class org.tukaani.xz.XZInputStream { *; }, -keep class org.tukaani.xz.XZOutputStream { *; }, -keep class org.tukaani.xz.LZMA2Options { *; }, -keep class org.armedbear.lisp.** { }, -keep class com.formdev.** { *; }, -keep class org.apfloat.** { *; }, -keep class apfloat { *; }, -optimizationpasses 9, -allowaccessmodification, -repackageclasses '', -dontwarn, -dontnote, -forceprocessing, -keep class palaiologos.kamilalisp.error.** { *; }, -keep class palaiologos.kamilalisp.runtime.remote.packet.** { *; }, -keepclasseswithmembers public class * { public static void main(java.lang.String[]); }, -keepclassmembers enum  * { public static **[] values(); public static ** valueOf(java.lang.String); }, -keepclasseswithmembers,includedescriptorclasses,allowshrinking class * { native <methods>; }]
[INFO] proguard jar: [/home/user/.m2/repository/com/guardsquare/proguard-base/7.4.0/proguard-base-7.4.0.jar, /home/user/.m2/repository/com/guardsquare/proguard-core/9.1.0/proguard-core-9.1.0.jar]
 [proguard] ProGuard, version 7.4.0
 [proguard] Unexpected error
 [proguard] java.io.IOException: Can't read [/usr/lib/jvm/java-22-openjdk/jmods] (Can't read [java.transaction.xa.jmod] (Can't process class [module-info.class] (Unsupported version number [66.0] (maximum 65.65535, Java null))))
 [proguard] 	at proguard.InputReader.readInput(InputReader.java:282) ~[proguard-base-7.4.0.jar:7.4.0]
 [proguard] 	at proguard.InputReader.readInput(InputReader.java:229) ~[proguard-base-7.4.0.jar:7.4.0]
 [proguard] 	at proguard.InputReader.readInput(InputReader.java:206) ~[proguard-base-7.4.0.jar:7.4.0]
 [proguard] 	at proguard.InputReader.execute(InputReader.java:157) ~[proguard-base-7.4.0.jar:7.4.0]
 [proguard] 	at proguard.pass.PassRunner.run(PassRunner.java:24) ~[proguard-base-7.4.0.jar:7.4.0]
 [proguard] 	at proguard.ProGuard.readInput(ProGuard.java:333) ~[proguard-base-7.4.0.jar:7.4.0]
 [proguard] 	at proguard.ProGuard.execute(ProGuard.java:124) ~[proguard-base-7.4.0.jar:7.4.0]
 [proguard] 	at proguard.ProGuard.main(ProGuard.java:651) ~[proguard-base-7.4.0.jar:7.4.0]
 [proguard] Caused by: java.io.IOException: Can't read [java.transaction.xa.jmod] (Can't process class [module-info.class] (Unsupported version number [66.0] (maximum 65.65535, Java null)))
 [proguard] 	at proguard.io.DirectorySource.readFiles(DirectorySource.java:84) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.DirectorySource.pumpDataEntries(DirectorySource.java:54) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.InputReader.readInput(InputReader.java:278) ~[proguard-base-7.4.0.jar:7.4.0]
 [proguard] 	... 7 more
 [proguard] Caused by: java.io.IOException: Can't process class [module-info.class] (Unsupported version number [66.0] (maximum 65.65535, Java null))
 [proguard] 	at proguard.io.ClassReader.read(ClassReader.java:163) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.RenamedDataEntryReader.read(RenamedDataEntryReader.java:96) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.PrefixStrippingDataEntryReader.read(PrefixStrippingDataEntryReader.java:59) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.PrefixStrippingDataEntryReader.read(PrefixStrippingDataEntryReader.java:59) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.JarReader.read(JarReader.java:84) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.DirectorySource.readFiles(DirectorySource.java:68) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.DirectorySource.readFiles(DirectorySource.java:80) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.DirectorySource.pumpDataEntries(DirectorySource.java:54) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.InputReader.readInput(InputReader.java:278) ~[proguard-base-7.4.0.jar:7.4.0]
 [proguard] 	... 7 more
 [proguard] Caused by: java.lang.UnsupportedOperationException: Unsupported version number [66.0] (maximum 65.65535, Java null)
 [proguard] 	at proguard.classfile.util.ClassUtil.checkVersionNumbers(ClassUtil.java:181) ~[proguard-core-9.1.0.jar:9.1.0]
 [proguard] 	at proguard.classfile.io.LibraryClassReader.visitLibraryClass(LibraryClassReader.java:112) ~[proguard-core-9.1.0.jar:9.1.0]
 [proguard] 	at proguard.classfile.LibraryClass.accept(LibraryClass.java:408) ~[proguard-core-9.1.0.jar:9.1.0]
 [proguard] 	at proguard.io.ClassReader.read(ClassReader.java:125) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.RenamedDataEntryReader.read(RenamedDataEntryReader.java:96) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.PrefixStrippingDataEntryReader.read(PrefixStrippingDataEntryReader.java:59) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.PrefixStrippingDataEntryReader.read(PrefixStrippingDataEntryReader.java:59) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.JarReader.read(JarReader.java:84) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.DirectorySource.readFiles(DirectorySource.java:68) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.DirectorySource.readFiles(DirectorySource.java:80) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.io.DirectorySource.pumpDataEntries(DirectorySource.java:54) ~[proguard-core-9.1.0.jar:7.4.0]
 [proguard] 	at proguard.InputReader.readInput(InputReader.java:278) ~[proguard-base-7.4.0.jar:7.4.0]
 [proguard] 	... 7 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39.502 s
[INFO] Finished at: 2024-07-08T00:02:12+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.wvengen:proguard-maven-plugin:2.6.0:proguard (default) on project kamilalisp: Obfuscation failed (result=1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Proguard seems outdated compared to the last java version available.
https://repology.org/project/proguard/versions

**Comment by iczelia** [comment]
Interesting. I should probably allow building without a proguard step. The reason why it's here in the first place is that it reduces the JAR size down from just under 100MB from all the 'stuff' pulled by 3rd party libraries that I do not intend to use. Thanks for the report.
